# Generated by Django 6.0.2 on 2026-02-14 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_request_pickup', 'can request waste pickup'), ('can_collect_waste', 'can collect waste'), ('can_verify_dump', 'can verify waste dump'), ('can_manage_system', 'can manage etting'), ('can_view_dashboard', 'can view dashboard')]},
        ),
    ]
