# Generated by Django 6.0.2 on 2026-02-15 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('dumped', 'Dumped'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('waste_type', models.CharField(choices=[('wet', 'Wet'), ('dry', 'Dry'), ('mixed', 'Mixed')], max_length=10)),
                ('weight_estimate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests', to=settings.AUTH_USER_MODEL)),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_pickups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
